// Code generated by go-swagger; DO NOT EDIT.

package bands

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddBandOKCode is the HTTP code returned for type AddBandOK
const AddBandOKCode int = 200

/*AddBandOK add band o k

swagger:response addBandOK
*/
type AddBandOK struct {
}

// NewAddBandOK creates AddBandOK with default headers values
func NewAddBandOK() *AddBandOK {

	return &AddBandOK{}
}

// WriteResponse to the client
func (o *AddBandOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
