// Code generated by go-swagger; DO NOT EDIT.

package bands

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/alpyilmaz1997/BandArchiveApi/models"
)

// GetBandByIDOKCode is the HTTP code returned for type GetBandByIDOK
const GetBandByIDOKCode int = 200

/*GetBandByIDOK successfull operation

swagger:response getBandByIdOK
*/
type GetBandByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Band `json:"body,omitempty"`
}

// NewGetBandByIDOK creates GetBandByIDOK with default headers values
func NewGetBandByIDOK() *GetBandByIDOK {

	return &GetBandByIDOK{}
}

// WithPayload adds the payload to the get band by Id o k response
func (o *GetBandByIDOK) WithPayload(payload *models.Band) *GetBandByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get band by Id o k response
func (o *GetBandByIDOK) SetPayload(payload *models.Band) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBandByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBandByIDBadRequestCode is the HTTP code returned for type GetBandByIDBadRequest
const GetBandByIDBadRequestCode int = 400

/*GetBandByIDBadRequest Bad Request

swagger:response getBandByIdBadRequest
*/
type GetBandByIDBadRequest struct {
}

// NewGetBandByIDBadRequest creates GetBandByIDBadRequest with default headers values
func NewGetBandByIDBadRequest() *GetBandByIDBadRequest {

	return &GetBandByIDBadRequest{}
}

// WriteResponse to the client
func (o *GetBandByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetBandByIDNotFoundCode is the HTTP code returned for type GetBandByIDNotFound
const GetBandByIDNotFoundCode int = 404

/*GetBandByIDNotFound Band Id cannot find

swagger:response getBandByIdNotFound
*/
type GetBandByIDNotFound struct {
}

// NewGetBandByIDNotFound creates GetBandByIDNotFound with default headers values
func NewGetBandByIDNotFound() *GetBandByIDNotFound {

	return &GetBandByIDNotFound{}
}

// WriteResponse to the client
func (o *GetBandByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
