// Code generated by go-swagger; DO NOT EDIT.

package bands

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/go-swagger/go-swagger/models"
)

// GetBandsOKCode is the HTTP code returned for type GetBandsOK
const GetBandsOKCode int = 200

/*GetBandsOK successfull operation

swagger:response getBandsOK
*/
type GetBandsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Band `json:"body,omitempty"`
}

// NewGetBandsOK creates GetBandsOK with default headers values
func NewGetBandsOK() *GetBandsOK {

	return &GetBandsOK{}
}

// WithPayload adds the payload to the get bands o k response
func (o *GetBandsOK) WithPayload(payload []*models.Band) *GetBandsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get bands o k response
func (o *GetBandsOK) SetPayload(payload []*models.Band) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBandsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Band, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetBandsNotFoundCode is the HTTP code returned for type GetBandsNotFound
const GetBandsNotFoundCode int = 404

/*GetBandsNotFound Bands cannot find

swagger:response getBandsNotFound
*/
type GetBandsNotFound struct {
}

// NewGetBandsNotFound creates GetBandsNotFound with default headers values
func NewGetBandsNotFound() *GetBandsNotFound {

	return &GetBandsNotFound{}
}

// WriteResponse to the client
func (o *GetBandsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
