// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Music Archive
//
//  This is a sample Music Archive server.
//  Terms Of Service:
//    http://swagger.io/terms/
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /v2
//  Version: 1.0.0
//  Contact: Alp Eren Yılmaz<alpyilmaz1997@gmail.com> http://alperenyilmaz.com
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
